# Generated by Django 3.2.2 on 2021-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(choices=[('H', 'HIIT'), ('C', 'cardio'), ('R', 'resistance')], default='H', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='training',
        ),
    ]
