# Generated by Django 3.2.2 on 2021-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210510_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
