# Generated by Django 3.2.2 on 2021-05-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210510_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraininType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('H', 'HIIT'), ('C', 'cardio'), ('R', 'resistance')], default='H', max_length=1)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workout')),
            ],
        ),
    ]
