# Generated by Django 3.2.2 on 2021-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_trainintype_trainingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtype',
            name='training_type',
            field=models.CharField(choices=[('H', 'HIIT'), ('C', 'cardio'), ('R', 'resistance')], default='H', max_length=1, verbose_name='Training Type'),
        ),
    ]
