# Generated by Django 3.2.2 on 2021-05-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210512_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='workouts',
            new_name='workout',
        ),
    ]
