# Generated by Django 3.2.2 on 2021-05-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_feeding_totalcalories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='totalcalories',
        ),
    ]
